// ─── Pipeline Stage Definitions ───────────────────────────────────────────────
// Edit this file to customise stage names, descriptions, icons, and output data.

export const PIPELINE_STAGES = [
  {
    id: 'query-analyzer',
    index: 0,
    icon: '🔍',
    iconBg: '#eef2ff',
    name: 'Query Analyzer',
    shortDesc: 'SAS field & table extraction',
    fullDesc:
      'Parses the SAS source file and extracts all field definitions, table structures, and embedded business logic rules for downstream processing.',
    durationMs: 1800, // ms per stage at 1x speed
    logLines: [
      { type: 'info', text: 'Opening SAS source file...' },
      { type: 'info', text: 'Scanning table declarations...' },
      { type: 'info', text: '47 tables · 312 fields identified' },
      { type: 'info', text: 'Extracting business logic rules...' },
      { type: 'ok',   text: 'Extraction complete — 89 rules captured' },
    ],
    result: {
      label: 'Extraction Output',
      rows: [
        { key: 'Tables identified',  value: '47',   color: 'blue'  },
        { key: 'Fields extracted',   value: '312',  color: 'blue'  },
        { key: 'Business rules',     value: '89',   color: 'blue'  },
        { key: 'Confidence score',   value: '94.2%',color: 'green' },
        { key: 'Parse duration',     value: '1.2s', color: ''      },
      ],
    },
  },
  {
    id: 'field-mapper',
    index: 1,
    icon: '🗺',
    iconBg: '#f0fdf4',
    name: 'Field Mapper',
    shortDesc: 'WGS schema with confidence scores',
    fullDesc:
      'Maps each source field to the WGS target schema using semantic similarity scoring. Fields below a confidence threshold are flagged for manual review.',
    durationMs: 1600,
    logLines: [
      { type: 'info', text: 'Loading WGS target schema v3.2...' },
      { type: 'info', text: 'Running semantic similarity matching...' },
      { type: 'info', text: 'Auto-mapped: 289 / 312 fields' },
      { type: 'warn', text: '23 fields flagged for manual review' },
      { type: 'ok',   text: 'Field mapping complete' },
    ],
    result: {
      label: 'Mapping Results',
      rows: [
        { key: 'Auto-mapped fields',    value: '289 / 312', color: 'green' },
        { key: 'Flagged for review',    value: '23 fields', color: 'amber' },
        { key: 'Avg confidence score',  value: '87.6%',     color: 'green' },
        { key: 'Schema version',        value: 'WGS v3.2',  color: ''      },
      ],
    },
  },
  {
    id: 'logic-converter',
    index: 2,
    icon: '⚙️',
    iconBg: '#fffbeb',
    name: 'Logic Converter',
    shortDesc: 'Python code & API endpoints',
    fullDesc:
      'Transpiles SAS business logic into idiomatic Python, automatically generating typed REST API endpoint stubs using the WGS SDK.',
    durationMs: 2200,
    logLines: [
      { type: 'info', text: 'Initialising Python transpiler...' },
      { type: 'info', text: 'Converting 89 business rules...' },
      { type: 'info', text: 'Generating REST endpoint stubs...' },
      { type: 'info', text: 'Writing converter_v1.py (2847 lines)' },
      { type: 'ok',   text: '12 endpoints generated — build succeeded' },
    ],
    result: {
      label: 'Generated Output',
      rows: [
        { key: 'Rules converted',   value: '89 rules',       color: 'blue'  },
        { key: 'API endpoints',     value: '12 endpoints',   color: 'blue'  },
        { key: 'Output file',       value: 'converter_v1.py',color: ''      },
        { key: 'Lines of code',     value: '2,847',          color: ''      },
        { key: 'Build status',      value: '✓ Success',      color: 'green' },
      ],
      codeSnippet: `# converter_v1.py — auto-generated by Logic Converter
from concept_sdk import WGSClient, auth

@auth.require_token
def process_query(payload: dict) -> dict:
    """Apply 89 business rules to concept payload."""
    client = WGSClient(schema_version="3.2")
    return client.convert(payload)

# POST /api/v1/convert
def endpoint_convert(request):
    return process_query(request.json)`,
    },
  },
  {
    id: 'test-orchestrator',
    index: 3,
    icon: '✅',
    iconBg: '#fdf4ff',
    name: 'Test Orchestrator',
    shortDesc: 'Test runs & performance metrics',
    fullDesc:
      'Runs the full regression test suite against generated logic and produces a final pipeline performance report with pass/fail breakdown.',
    durationMs: 2000,
    logLines: [
      { type: 'info', text: 'Loading test suite (312 cases)...' },
      { type: 'info', text: 'Running unit tests...' },
      { type: 'info', text: 'Running integration tests...' },
      { type: 'warn', text: '14 tests failed — reviewing edge cases' },
      { type: 'ok',   text: 'Pipeline score: 91.3% — PASSED ✓' },
    ],
    result: {
      label: 'Test Report',
      rows: [
        { key: 'Total tests',      value: '312',    color: ''      },
        { key: 'Passed',           value: '298',    color: 'green' },
        { key: 'Failed',           value: '14',     color: 'amber' },
        { key: 'Avg response',     value: '98ms',   color: 'green' },
        { key: 'Pipeline score',   value: '91.3% ✓',color: 'green' },
      ],
    },
  },
];

export const SPEED_OPTIONS = [
  { label: '0.5x', value: 0.5 },
  { label: '1x',   value: 1   },
  { label: '2x',   value: 2   },
  { label: '3x',   value: 3   },
];
